package daoModels;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 55): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 55;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        tbl_attachmentsDao.createTable(db, ifNotExists);
        tbl_grid_header_modelDao.createTable(db, ifNotExists);
        tbl_grower_modelDao.createTable(db, ifNotExists);
        tbl_info_modelDao.createTable(db, ifNotExists);
        tbl_land_modelDao.createTable(db, ifNotExists);
        tbl_leaf_modelDao.createTable(db, ifNotExists);
        tbl_media_modelDao.createTable(db, ifNotExists);
        tbl_signature_modelDao.createTable(db, ifNotExists);
        tbl_task_modelDao.createTable(db, ifNotExists);
        tbl_user_modelDao.createTable(db, ifNotExists);
        tbl_worksheet_modelDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        tbl_attachmentsDao.dropTable(db, ifExists);
        tbl_grid_header_modelDao.dropTable(db, ifExists);
        tbl_grower_modelDao.dropTable(db, ifExists);
        tbl_info_modelDao.dropTable(db, ifExists);
        tbl_land_modelDao.dropTable(db, ifExists);
        tbl_leaf_modelDao.dropTable(db, ifExists);
        tbl_media_modelDao.dropTable(db, ifExists);
        tbl_signature_modelDao.dropTable(db, ifExists);
        tbl_task_modelDao.dropTable(db, ifExists);
        tbl_user_modelDao.dropTable(db, ifExists);
        tbl_worksheet_modelDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(tbl_attachmentsDao.class);
        registerDaoClass(tbl_grid_header_modelDao.class);
        registerDaoClass(tbl_grower_modelDao.class);
        registerDaoClass(tbl_info_modelDao.class);
        registerDaoClass(tbl_land_modelDao.class);
        registerDaoClass(tbl_leaf_modelDao.class);
        registerDaoClass(tbl_media_modelDao.class);
        registerDaoClass(tbl_signature_modelDao.class);
        registerDaoClass(tbl_task_modelDao.class);
        registerDaoClass(tbl_user_modelDao.class);
        registerDaoClass(tbl_worksheet_modelDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
