package daoModels;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import models.tbl_attachments;
import models.tbl_grid_header_model;
import models.tbl_grower_model;
import models.tbl_info_model;
import models.tbl_land_model;
import models.tbl_leaf_model;
import models.tbl_media_model;
import models.tbl_signature_model;
import models.tbl_task_model;
import models.tbl_user_model;
import models.tbl_worksheet_model;

import daoModels.tbl_attachmentsDao;
import daoModels.tbl_grid_header_modelDao;
import daoModels.tbl_grower_modelDao;
import daoModels.tbl_info_modelDao;
import daoModels.tbl_land_modelDao;
import daoModels.tbl_leaf_modelDao;
import daoModels.tbl_media_modelDao;
import daoModels.tbl_signature_modelDao;
import daoModels.tbl_task_modelDao;
import daoModels.tbl_user_modelDao;
import daoModels.tbl_worksheet_modelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tbl_attachmentsDaoConfig;
    private final DaoConfig tbl_grid_header_modelDaoConfig;
    private final DaoConfig tbl_grower_modelDaoConfig;
    private final DaoConfig tbl_info_modelDaoConfig;
    private final DaoConfig tbl_land_modelDaoConfig;
    private final DaoConfig tbl_leaf_modelDaoConfig;
    private final DaoConfig tbl_media_modelDaoConfig;
    private final DaoConfig tbl_signature_modelDaoConfig;
    private final DaoConfig tbl_task_modelDaoConfig;
    private final DaoConfig tbl_user_modelDaoConfig;
    private final DaoConfig tbl_worksheet_modelDaoConfig;

    private final tbl_attachmentsDao tbl_attachmentsDao;
    private final tbl_grid_header_modelDao tbl_grid_header_modelDao;
    private final tbl_grower_modelDao tbl_grower_modelDao;
    private final tbl_info_modelDao tbl_info_modelDao;
    private final tbl_land_modelDao tbl_land_modelDao;
    private final tbl_leaf_modelDao tbl_leaf_modelDao;
    private final tbl_media_modelDao tbl_media_modelDao;
    private final tbl_signature_modelDao tbl_signature_modelDao;
    private final tbl_task_modelDao tbl_task_modelDao;
    private final tbl_user_modelDao tbl_user_modelDao;
    private final tbl_worksheet_modelDao tbl_worksheet_modelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tbl_attachmentsDaoConfig = daoConfigMap.get(tbl_attachmentsDao.class).clone();
        tbl_attachmentsDaoConfig.initIdentityScope(type);

        tbl_grid_header_modelDaoConfig = daoConfigMap.get(tbl_grid_header_modelDao.class).clone();
        tbl_grid_header_modelDaoConfig.initIdentityScope(type);

        tbl_grower_modelDaoConfig = daoConfigMap.get(tbl_grower_modelDao.class).clone();
        tbl_grower_modelDaoConfig.initIdentityScope(type);

        tbl_info_modelDaoConfig = daoConfigMap.get(tbl_info_modelDao.class).clone();
        tbl_info_modelDaoConfig.initIdentityScope(type);

        tbl_land_modelDaoConfig = daoConfigMap.get(tbl_land_modelDao.class).clone();
        tbl_land_modelDaoConfig.initIdentityScope(type);

        tbl_leaf_modelDaoConfig = daoConfigMap.get(tbl_leaf_modelDao.class).clone();
        tbl_leaf_modelDaoConfig.initIdentityScope(type);

        tbl_media_modelDaoConfig = daoConfigMap.get(tbl_media_modelDao.class).clone();
        tbl_media_modelDaoConfig.initIdentityScope(type);

        tbl_signature_modelDaoConfig = daoConfigMap.get(tbl_signature_modelDao.class).clone();
        tbl_signature_modelDaoConfig.initIdentityScope(type);

        tbl_task_modelDaoConfig = daoConfigMap.get(tbl_task_modelDao.class).clone();
        tbl_task_modelDaoConfig.initIdentityScope(type);

        tbl_user_modelDaoConfig = daoConfigMap.get(tbl_user_modelDao.class).clone();
        tbl_user_modelDaoConfig.initIdentityScope(type);

        tbl_worksheet_modelDaoConfig = daoConfigMap.get(tbl_worksheet_modelDao.class).clone();
        tbl_worksheet_modelDaoConfig.initIdentityScope(type);

        tbl_attachmentsDao = new tbl_attachmentsDao(tbl_attachmentsDaoConfig, this);
        tbl_grid_header_modelDao = new tbl_grid_header_modelDao(tbl_grid_header_modelDaoConfig, this);
        tbl_grower_modelDao = new tbl_grower_modelDao(tbl_grower_modelDaoConfig, this);
        tbl_info_modelDao = new tbl_info_modelDao(tbl_info_modelDaoConfig, this);
        tbl_land_modelDao = new tbl_land_modelDao(tbl_land_modelDaoConfig, this);
        tbl_leaf_modelDao = new tbl_leaf_modelDao(tbl_leaf_modelDaoConfig, this);
        tbl_media_modelDao = new tbl_media_modelDao(tbl_media_modelDaoConfig, this);
        tbl_signature_modelDao = new tbl_signature_modelDao(tbl_signature_modelDaoConfig, this);
        tbl_task_modelDao = new tbl_task_modelDao(tbl_task_modelDaoConfig, this);
        tbl_user_modelDao = new tbl_user_modelDao(tbl_user_modelDaoConfig, this);
        tbl_worksheet_modelDao = new tbl_worksheet_modelDao(tbl_worksheet_modelDaoConfig, this);

        registerDao(tbl_attachments.class, tbl_attachmentsDao);
        registerDao(tbl_grid_header_model.class, tbl_grid_header_modelDao);
        registerDao(tbl_grower_model.class, tbl_grower_modelDao);
        registerDao(tbl_info_model.class, tbl_info_modelDao);
        registerDao(tbl_land_model.class, tbl_land_modelDao);
        registerDao(tbl_leaf_model.class, tbl_leaf_modelDao);
        registerDao(tbl_media_model.class, tbl_media_modelDao);
        registerDao(tbl_signature_model.class, tbl_signature_modelDao);
        registerDao(tbl_task_model.class, tbl_task_modelDao);
        registerDao(tbl_user_model.class, tbl_user_modelDao);
        registerDao(tbl_worksheet_model.class, tbl_worksheet_modelDao);
    }
    
    public void clear() {
        tbl_attachmentsDaoConfig.clearIdentityScope();
        tbl_grid_header_modelDaoConfig.clearIdentityScope();
        tbl_grower_modelDaoConfig.clearIdentityScope();
        tbl_info_modelDaoConfig.clearIdentityScope();
        tbl_land_modelDaoConfig.clearIdentityScope();
        tbl_leaf_modelDaoConfig.clearIdentityScope();
        tbl_media_modelDaoConfig.clearIdentityScope();
        tbl_signature_modelDaoConfig.clearIdentityScope();
        tbl_task_modelDaoConfig.clearIdentityScope();
        tbl_user_modelDaoConfig.clearIdentityScope();
        tbl_worksheet_modelDaoConfig.clearIdentityScope();
    }

    public tbl_attachmentsDao getTbl_attachmentsDao() {
        return tbl_attachmentsDao;
    }

    public tbl_grid_header_modelDao getTbl_grid_header_modelDao() {
        return tbl_grid_header_modelDao;
    }

    public tbl_grower_modelDao getTbl_grower_modelDao() {
        return tbl_grower_modelDao;
    }

    public tbl_info_modelDao getTbl_info_modelDao() {
        return tbl_info_modelDao;
    }

    public tbl_land_modelDao getTbl_land_modelDao() {
        return tbl_land_modelDao;
    }

    public tbl_leaf_modelDao getTbl_leaf_modelDao() {
        return tbl_leaf_modelDao;
    }

    public tbl_media_modelDao getTbl_media_modelDao() {
        return tbl_media_modelDao;
    }

    public tbl_signature_modelDao getTbl_signature_modelDao() {
        return tbl_signature_modelDao;
    }

    public tbl_task_modelDao getTbl_task_modelDao() {
        return tbl_task_modelDao;
    }

    public tbl_user_modelDao getTbl_user_modelDao() {
        return tbl_user_modelDao;
    }

    public tbl_worksheet_modelDao getTbl_worksheet_modelDao() {
        return tbl_worksheet_modelDao;
    }

}
