package daoModels;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import models.tbl_signature_model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TBL_SIGNATURE_MODEL".
*/
public class tbl_signature_modelDao extends AbstractDao<tbl_signature_model, Long> {

    public static final String TABLENAME = "TBL_SIGNATURE_MODEL";

    /**
     * Properties of entity tbl_signature_model.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Grower_id = new Property(1, String.class, "grower_id", false, "GROWER_ID");
        public final static Property Land_id = new Property(2, String.class, "land_id", false, "LAND_ID");
        public final static Property Grower_signature_uri = new Property(3, String.class, "grower_signature_uri", false, "GROWER_SIGNATURE_URI");
        public final static Property Inspector_signature_uri = new Property(4, String.class, "inspector_signature_uri", false, "INSPECTOR_SIGNATURE_URI");
        public final static Property Second_inspector_name = new Property(5, String.class, "second_inspector_name", false, "SECOND_INSPECTOR_NAME");
        public final static Property Second_inspector_siginature_uri = new Property(6, String.class, "second_inspector_siginature_uri", false, "SECOND_INSPECTOR_SIGINATURE_URI");
        public final static Property Draw_map_uri = new Property(7, String.class, "draw_map_uri", false, "DRAW_MAP_URI");
    }


    public tbl_signature_modelDao(DaoConfig config) {
        super(config);
    }
    
    public tbl_signature_modelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TBL_SIGNATURE_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"GROWER_ID\" TEXT," + // 1: grower_id
                "\"LAND_ID\" TEXT," + // 2: land_id
                "\"GROWER_SIGNATURE_URI\" TEXT," + // 3: grower_signature_uri
                "\"INSPECTOR_SIGNATURE_URI\" TEXT," + // 4: inspector_signature_uri
                "\"SECOND_INSPECTOR_NAME\" TEXT," + // 5: second_inspector_name
                "\"SECOND_INSPECTOR_SIGINATURE_URI\" TEXT," + // 6: second_inspector_siginature_uri
                "\"DRAW_MAP_URI\" TEXT);"); // 7: draw_map_uri
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TBL_SIGNATURE_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, tbl_signature_model entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String grower_id = entity.getGrower_id();
        if (grower_id != null) {
            stmt.bindString(2, grower_id);
        }
 
        String land_id = entity.getLand_id();
        if (land_id != null) {
            stmt.bindString(3, land_id);
        }
 
        String grower_signature_uri = entity.getGrower_signature_uri();
        if (grower_signature_uri != null) {
            stmt.bindString(4, grower_signature_uri);
        }
 
        String inspector_signature_uri = entity.getInspector_signature_uri();
        if (inspector_signature_uri != null) {
            stmt.bindString(5, inspector_signature_uri);
        }
 
        String second_inspector_name = entity.getSecond_inspector_name();
        if (second_inspector_name != null) {
            stmt.bindString(6, second_inspector_name);
        }
 
        String second_inspector_siginature_uri = entity.getSecond_inspector_siginature_uri();
        if (second_inspector_siginature_uri != null) {
            stmt.bindString(7, second_inspector_siginature_uri);
        }
 
        String draw_map_uri = entity.getDraw_map_uri();
        if (draw_map_uri != null) {
            stmt.bindString(8, draw_map_uri);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, tbl_signature_model entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String grower_id = entity.getGrower_id();
        if (grower_id != null) {
            stmt.bindString(2, grower_id);
        }
 
        String land_id = entity.getLand_id();
        if (land_id != null) {
            stmt.bindString(3, land_id);
        }
 
        String grower_signature_uri = entity.getGrower_signature_uri();
        if (grower_signature_uri != null) {
            stmt.bindString(4, grower_signature_uri);
        }
 
        String inspector_signature_uri = entity.getInspector_signature_uri();
        if (inspector_signature_uri != null) {
            stmt.bindString(5, inspector_signature_uri);
        }
 
        String second_inspector_name = entity.getSecond_inspector_name();
        if (second_inspector_name != null) {
            stmt.bindString(6, second_inspector_name);
        }
 
        String second_inspector_siginature_uri = entity.getSecond_inspector_siginature_uri();
        if (second_inspector_siginature_uri != null) {
            stmt.bindString(7, second_inspector_siginature_uri);
        }
 
        String draw_map_uri = entity.getDraw_map_uri();
        if (draw_map_uri != null) {
            stmt.bindString(8, draw_map_uri);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public tbl_signature_model readEntity(Cursor cursor, int offset) {
        tbl_signature_model entity = new tbl_signature_model( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // grower_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // land_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // grower_signature_uri
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // inspector_signature_uri
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // second_inspector_name
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // second_inspector_siginature_uri
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // draw_map_uri
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, tbl_signature_model entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGrower_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLand_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGrower_signature_uri(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setInspector_signature_uri(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSecond_inspector_name(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSecond_inspector_siginature_uri(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDraw_map_uri(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(tbl_signature_model entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(tbl_signature_model entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(tbl_signature_model entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
