package daoModels;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import models.tbl_attachments;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TBL_ATTACHMENTS".
*/
public class tbl_attachmentsDao extends AbstractDao<tbl_attachments, Long> {

    public static final String TABLENAME = "TBL_ATTACHMENTS";

    /**
     * Properties of entity tbl_attachments.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Filename = new Property(1, String.class, "filename", false, "FILENAME");
        public final static Property Filepath = new Property(2, String.class, "filepath", false, "FILEPATH");
        public final static Property Land_id = new Property(3, String.class, "land_id", false, "LAND_ID");
        public final static Property Grower_id = new Property(4, String.class, "grower_id", false, "GROWER_ID");
        public final static Property FileType = new Property(5, String.class, "fileType", false, "FILE_TYPE");
        public final static Property IsSynced = new Property(6, boolean.class, "isSynced", false, "IS_SYNCED");
        public final static Property IsSynced2 = new Property(7, boolean.class, "isSynced2", false, "IS_SYNCED2");
    }


    public tbl_attachmentsDao(DaoConfig config) {
        super(config);
    }
    
    public tbl_attachmentsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TBL_ATTACHMENTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"FILENAME\" TEXT," + // 1: filename
                "\"FILEPATH\" TEXT," + // 2: filepath
                "\"LAND_ID\" TEXT," + // 3: land_id
                "\"GROWER_ID\" TEXT," + // 4: grower_id
                "\"FILE_TYPE\" TEXT," + // 5: fileType
                "\"IS_SYNCED\" INTEGER NOT NULL ," + // 6: isSynced
                "\"IS_SYNCED2\" INTEGER NOT NULL );"); // 7: isSynced2
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TBL_ATTACHMENTS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, tbl_attachments entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String filename = entity.getFilename();
        if (filename != null) {
            stmt.bindString(2, filename);
        }
 
        String filepath = entity.getFilepath();
        if (filepath != null) {
            stmt.bindString(3, filepath);
        }
 
        String land_id = entity.getLand_id();
        if (land_id != null) {
            stmt.bindString(4, land_id);
        }
 
        String grower_id = entity.getGrower_id();
        if (grower_id != null) {
            stmt.bindString(5, grower_id);
        }
 
        String fileType = entity.getFileType();
        if (fileType != null) {
            stmt.bindString(6, fileType);
        }
        stmt.bindLong(7, entity.getIsSynced() ? 1L: 0L);
        stmt.bindLong(8, entity.getIsSynced2() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, tbl_attachments entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String filename = entity.getFilename();
        if (filename != null) {
            stmt.bindString(2, filename);
        }
 
        String filepath = entity.getFilepath();
        if (filepath != null) {
            stmt.bindString(3, filepath);
        }
 
        String land_id = entity.getLand_id();
        if (land_id != null) {
            stmt.bindString(4, land_id);
        }
 
        String grower_id = entity.getGrower_id();
        if (grower_id != null) {
            stmt.bindString(5, grower_id);
        }
 
        String fileType = entity.getFileType();
        if (fileType != null) {
            stmt.bindString(6, fileType);
        }
        stmt.bindLong(7, entity.getIsSynced() ? 1L: 0L);
        stmt.bindLong(8, entity.getIsSynced2() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public tbl_attachments readEntity(Cursor cursor, int offset) {
        tbl_attachments entity = new tbl_attachments( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // filename
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // filepath
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // land_id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // grower_id
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // fileType
            cursor.getShort(offset + 6) != 0, // isSynced
            cursor.getShort(offset + 7) != 0 // isSynced2
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, tbl_attachments entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFilename(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFilepath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLand_id(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGrower_id(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFileType(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIsSynced(cursor.getShort(offset + 6) != 0);
        entity.setIsSynced2(cursor.getShort(offset + 7) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(tbl_attachments entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(tbl_attachments entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(tbl_attachments entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
